framework:
  messenger:
#    failure_transport: failed
    default_bus: messenger.bus.default

    transports:
      async:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        options:
          stream: messenger

    routing:
      'App\Common\Domain\Event\UserDeletedEvent': async

when@test:
  framework:
    messenger:
      transports:
        test_async:
          dsn: 'in-memory://'

      routing:
        'App\Common\Domain\Event\UserDeletedEvent': test_async
