services:
  # Symfony App Container
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "${APP_NAME:-symfony}-app"
    ports:
      # Local port => container port
      - "${DOCKER_APP_PORT:-8000}:8000"
    depends_on:
      - mysql

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "${APP_NAME:-symfony}-consumer"
    restart: unless-stopped
    depends_on:
      - mysql
      - valkey
    entrypoint: [ "php", "bin/console", "messenger:consume", "async", "-vv", "--memory-limit=64M" ]

  # MySQL Container
  mysql:
    image: mysql:8.3
    container_name: "${APP_NAME:-symfony}-mysql"
    ports:
      - "${DOCKER_MYSQL_PORT:-3306}:3306"
    environment:
      MYSQL_DATABASE: "${DOCKER_MYSQL_DATABASE:-symfony_db}"
      MYSQL_USER: "${DOCKER_MYSQL_USER:-symfony}"
      MYSQL_PASSWORD: "${DOCKER_MYSQL_PASSWORD:-secret}"
      MYSQL_ROOT_PASSWORD: "${DOCKER_MYSQL_ROOT_PASSWORD:-rootsecret}"
    volumes:
      - mysql_data:/var/lib/mysql

  valkey:
    image: valkey/valkey:8
    container_name: "${APP_NAME:-symfony}-valkey"
    ports:
      - "${DOCKER_VALKEY_PORT:-6379}:6379"

volumes:
  mysql_data:

