parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Common\Infrastructure\Symfony\Controller\:
    resource: '../src/Common/Infrastructure/Symfony/Controller/'
    exclude: '../src/Common/Infrastructure/Symfony/Controller/{Meta.php,CollectionResponse.php}'
    tags: [ 'controller.service_arguments' ]

  App\User\Infrastructure\Symfony\Controller\:
    resource: '../src/User/Infrastructure/Symfony/Controller/'
    exclude: '../src/User/Infrastructure/Symfony/Controller/{Meta.php,CollectionResponse.php}'
    tags: [ 'controller.service_arguments' ]

  # Commands
  ## Command Handlers
  App\Common\Application\Handler\:
    resource: '../src/Common/Application/Handler/*'
    exclude:
      - '../src/Common/Application/Handler/{Handler.php}'
      - '../src/Common/Application/Handler/*/Exception'
    tags: [ 'app.command_handler' ]

  App\User\Application\Handler\:
    resource: '../src/User/Application/Handler/*'
    exclude:
      - '../src/User/Application/Handler/*/Exception'
    tags: [ 'app.command_handler' ]

  ## Middlewares
#  App\Application\CommandBus\Middleware\DummyMiddleware:
#    tags: [ { name: 'app.command_middleware', priority: 10 } ]
#
#  App\Infrastructure\CommandBus\Middleware\PriorityDummyMiddleware:
#    tags: [ { name: 'app.command_middleware', priority: 11 } ]
#
#  App\Infrastructure\CommandBus\Middleware\LoggingMiddleware:
#    tags: [ { name: 'app.command_middleware', priority: 1 } ]

  ## Command Bus
  App\Common\Application\CommandBus\CommandBusInterface:
    class: App\Common\Infrastructure\CommandBus\CommandBus
    tags:
      - { name: 'container.preload', class: 'App\Common\Infrastructure\CommandBus\CommandBus' }

  # /Commands

  # Events
  ## Event Bus
  App\Common\Application\EventBus\EventBusInterface:
    class: App\Common\Infrastructure\EventBus\EventBus
    tags:
      - { name: 'container.preload', class: 'App\Common\Infrastructure\EventBus\EventBus' }

  # /Events

  # Repositories
  Doctrine\ORM\EntityManagerInterface:
    alias: 'doctrine.orm.default_entity_manager'
    public: false

  ## User
  App\User\Domain\Repository\UserRepositoryInterface: '@App\User\Infrastructure\Doctrine\Repository\UserRepository'
  App\User\Infrastructure\Doctrine\Repository\UserRepository:
    arguments:
      $entityManager: '@Doctrine\ORM\EntityManagerInterface'

  # /Repositories

  # Services
  App\Common\Application\Service\:
    resource: '../src/Common/Application/Service/'

  App\User\Application\Service\:
    resource: '../src/User/Application/Service/'

  # / Services

  # Event Listeners
  App\Common\Infrastructure\Symfony\EventListener\ExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception }
  # / Event Listeners
