parameters:
  jwt_token_secret: '%env(APP_JWT_TOKEN_SECRET)%'
  jwt_token_ttl: '%env(resolve:int:APP_JWT_TOKEN_TTL)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Common\Infrastructure\Symfony\Controller\:
    resource: '../src/Common/Infrastructure/Symfony/Controller/'
    tags: [ 'controller.service_arguments' ]

  App\User\Infrastructure\Symfony\Controller\:
    resource: '../src/User/Infrastructure/Symfony/Controller/'
    tags: [ 'controller.service_arguments' ]

  App\WorkEntry\Infrastructure\Symfony\Controller\:
    resource: '../src/WorkEntry/Infrastructure/Symfony/Controller/'
    tags: [ 'controller.service_arguments' ]

  # Commands
  ## Command Handlers
  App\Common\Application\Handler\:
    resource: '../src/Common/Application/Handler/*'
    exclude:
      - '../src/Common/Application/Handler/{Handler.php}'
      - '../src/Common/Application/Handler/*/Exception'
    tags: [ 'app.command_handler' ]

  App\User\Application\Handler\:
    resource: '../src/User/Application/Handler/*'
    exclude:
      - '../src/User/Application/Handler/*/Exception'
    tags: [ 'app.command_handler' ]

  App\WorkEntry\Application\Handler\:
    resource: '../src/WorkEntry/Application/Handler/*'
    exclude:
      - '../src/WorkEntry/Application/Handler/*/Exception'
    tags: [ 'app.command_handler' ]

  ## Middlewares
#  App\Application\CommandBus\Middleware\DummyMiddleware:
#    tags: [ { name: 'app.command_middleware', priority: 10 } ]
#
#  App\Infrastructure\CommandBus\Middleware\PriorityDummyMiddleware:
#    tags: [ { name: 'app.command_middleware', priority: 11 } ]
#
#  App\Infrastructure\CommandBus\Middleware\LoggingMiddleware:
#    tags: [ { name: 'app.command_middleware', priority: 1 } ]

  ## Command Bus
  App\Common\Application\CommandBus\CommandBusInterface:
    class: App\Common\Infrastructure\CommandBus\CommandBus
    tags:
      - { name: 'container.preload', class: 'App\Common\Infrastructure\CommandBus\CommandBus' }

  # /Commands

  # Events
  ## Event Bus
  App\Common\Application\EventBus\EventBusInterface:
    class: App\Common\Infrastructure\EventBus\EventBus
    tags:
      - { name: 'container.preload', class: 'App\Common\Infrastructure\EventBus\EventBus' }

  # Async Default Subscriber
  App\Common\Application\Subscriber\AsyncEventSubscriber:
    arguments:
      $eventBus: '@App\Common\Application\EventBus\EventBusInterface'
    tags:
      - { name: messenger.message_handler }

  # Subscribers
  App\WorkEntry\Application\Subscriber\UserWorkEntryCreatedSubscriber:
    tags: [ 'app.event_subscriber' ]
  ##
  # /Events

  # Repositories
  Doctrine\ORM\EntityManagerInterface:
    alias: 'doctrine.orm.default_entity_manager'
    public: false

  ## User
  App\User\Domain\Repository\UserRepositoryInterface: '@App\User\Infrastructure\Doctrine\Repository\UserRepository'
  App\User\Infrastructure\Doctrine\Repository\UserRepository:
    arguments:
      $entityManager: '@Doctrine\ORM\EntityManagerInterface'

  ## WorkEntry
  App\WorkEntry\Domain\Repository\WorkEntryRepositoryInterface: '@App\WorkEntry\Infrastructure\Doctrine\Repository\WorkEntryRepository'
  App\WorkEntry\Infrastructure\Doctrine\Repository\WorkEntryRepository:
    arguments:
      $entityManager: '@Doctrine\ORM\EntityManagerInterface'

  # /Repositories

  # Services
  App\User\Application\Service\:
    resource: '../src/User/Application/Service/'

  # / Services

  # Event Listeners
  App\Common\Infrastructure\Symfony\EventListener\ExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception }
  # / Event Listeners

  # Security
  ## TokenManager
  App\Common\Application\Security\TokenManagerInterface: '@App\Common\Infrastructure\Security\JwtManager'
  App\Common\Infrastructure\Security\JwtManager:
    arguments:
      - '%jwt_token_secret%'
      - '%jwt_token_ttl%'

